### ISSUE TITLE
failing to start 

### ISSUE THREAD

**Issue by farloid** [resin-io-playground/resin-octoprint#18]
once the code has been pushed to my pi 3 the dialog box kicks out:

 octoprint  Command not found: /app/udevd.sh
Service exited 'octoprint sha256:e75aff15d8e675bf3a29a3fdf7097314ece0b4a951296cd260bac93de7fd9089'

not entriely sure what is up, i tried running the diagnostic tool in balena cloud however that didnt make it any clearer what was up. 
thanks.

**Comment by 20k-ultra** [comment]
hey @farloid I just got a change merged that I think will fix this issue. Do you want to try pushing the latest to your device again

**Comment by farloid** [comment]
@20k-ultra works! thankyou very much for your help!

**Comment by 20k-ultra** [comment]
thanks for confirming :)
